package goop;

import java.io.IOException;
import java.nio.file.Path;

import goop.command.Command;
import goop.exception.GoopException;
import goop.parser.Parser;
import goop.storage.Storage;
import goop.task.TaskList;
import goop.ui.ResponseUi;
import goop.ui.Ui;

/**
 * Coordinates the components of the Goop chatbot application.
 */
public class Goop {
    /** Relative, OS-independent path used for the user's saved task list. */
    private static final Path DATA_FILE_PATH = Path.of("data", "goop.txt");

    private final Parser parser;
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private final String loadWarning;

    /**
     * Creates a chatbot using the default relative data path.
     */
    public Goop() {
        this(DATA_FILE_PATH);
    }

    /**
     * Creates a chatbot using the given task data file.
     *
     * @param filePath Path used to load and save tasks.
     */
    public Goop(Path filePath) {
        parser = new Parser();
        storage = new Storage(filePath);
        ui = new Ui();

        TaskList loadedTasks;
        String warning = null;
        try {
            loadedTasks = new TaskList(storage.loadTasks());
        } catch (IOException error) {
            loadedTasks = new TaskList();
            warning = error.getMessage();
        }
        tasks = loadedTasks;
        loadWarning = warning;
    }

    /**
     * Greets the user and handles commands until input ends or {@code bye} is
     * entered.
     */
    public void run() {
        ui.showWelcome();
        if (loadWarning != null) {
            ui.showLoadingError(loadWarning);
        }

        boolean isExit = false;
        while (!isExit && ui.hasNextCommand()) {
            String command = ui.readCommand();
            ui.showDivider();

            try {
                Command parsedCommand = parser.parse(command);
                parsedCommand.execute(tasks, ui, storage);
                isExit = parsedCommand.isExit();
            } catch (GoopException error) {
                ui.showError(error.getMessage());
            } catch (IOException error) {
                ui.showError(error.getMessage() + " No changes were made.");
            }
        }
    }

    /**
     * Returns the greeting shown when the GUI starts.
     *
     * @return Greeting and any saved-data warning.
     */
    public String getWelcomeMessage() {
        String welcomeMessage = "Hello! I'm Goop.\nWhat can I do for you?";
        if (loadWarning == null) {
            return welcomeMessage;
        }
        return welcomeMessage + "\n\nWARNING: " + loadWarning
                + "\nStarting with an empty task list.";
    }

    /**
     * Executes one command and returns its result for a graphical interface.
     *
     * @param input Command entered by the user.
     * @return Response and exit status generated by the command.
     */
    public CommandResult getResponse(String input) {
        ResponseUi responseUi = new ResponseUi();
        boolean isExit = false;
        try {
            Command parsedCommand = parser.parse(input);
            parsedCommand.execute(tasks, responseUi, storage);
            isExit = parsedCommand.isExit();
        } catch (GoopException error) {
            responseUi.showError(error.getMessage());
        } catch (IOException error) {
            responseUi.showError(error.getMessage() + " No changes were made.");
        }
        return new CommandResult(responseUi.getResponse(), isExit);
    }

    /**
     * Starts Goop using the default relative data path.
     *
     * @param args Command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        new Goop().run();
    }
}
